spring.application.name=StaySavvy


#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Airbnb
spring.datasource.username=postgres
spring.datasource.password:Mohan098@#
spring.jpa.hibernate.ddl-auto=create

#Show the SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Show the values (parameters) being bound to the '?' in SQL
#In Hibernate 6/7, the package path for binding logs has changed slightly
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.servlet.context-path=/api/v1

jwt.secretKey=UO*$Ndio384noijOJ*$3o2r34f2iN*#N*$ohrdunewnfl483iJ*$d3noinw84buHH*(DIJX9845h3biuH*(3uf4ibjdhod4


frontend.url=http://localhost:8080
stripe.secret.key=sk_test_51SoSBG33zTmDJAld7A6ikTFt9XPvod3GE4jyOlBLrk4esV8mRy6ZSCqwEZow0goWVucpJSBLABd26L7DFdGejVFC00EvXRohGm
stripe.webhook.secret=whsec_7373c950cab226d152ff8ad923c5110a61cb5daff55c912f0bcef8c828bf53dc


## 3. Show detailed error logs for Hibernate's semantic analysis
## This helps catch "Could not resolve class" errors early
#logging.level.org.hibernate.query.hql=DEBUG

## 4. Optional: Log the results of your queries to see what's being returned
#logging.level.org.hibernate.orm.jdbc.extract=TRACE