spring.application.name=StaySavvy


#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Airbnb
spring.datasource.username=postgres
spring.datasource.password:Mohan098@#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=UO*$Ndio384noijOJ*$3o2r34f2iN*#N*$ohrdunewnfl483iJ*$d3noinw84buHH*(DIJX9845h3biuH*(3uf4ibjdhod4


frontend.url=http://localhost:8080
stripe.secret.key=sk_test_51MUudOSJZxUFzIY7wh2ZnvJLJh4eFFTTbQXneIiOak813B94ZSxIpDwyFvyquDjMjrX1fluFXTGZhwjfFK7fx9r200X9ihBZTT
stripe.webhook.secret=whsec_2a594ea1642948640fd49c4b7f63d7a9026d1e8be70061716cde895e9833e500