spring.application.name=StaySavvy


#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Airbnb
spring.datasource.username=postgres
spring.datasource.password:Mohan098@#
spring.jpa.hibernate.ddl-auto=update

#Show the SQL queries in the console
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=UO*$Ndio384noijOJ*$3o2r34f2iN*#N*$ohrdunewnfl483iJ*$d3noinw84buHH*(DIJX9845h3biuH*(3uf4ibjdhod4


frontend.url=http://localhost:8080
stripe.secret.key=sk_test_51SoSBG33zTmDJAld7A6ikTFt9XPvod3GE4jyOlBLrk4esV8mRy6ZSCqwEZow0goWVucpJSBLABd26L7DFdGejVFC00EvXRohGm
stripe.webhook.secret=whsec_7373c950cab226d152ff8ad923c5110a61cb5daff55c912f0bcef8c828bf53dc\
  #stripe listen --forward-to localhost:8080/api/v1/webhook/payment

my.variable=dev

